### ISSUE TITLE
Prescription entity won't compile

### ISSUE THREAD

**Issue by tanviriss** [se-2024/PATIENT_SERVICE_API#20]
## Describe the bug
I created the prescription entity and tried to run it with ./scripts/run.sh and it gives me a bunch of errors. 

### Steps to reproduce
Steps to reproduce the behavior.

### Environment
 - OS: [e.g. Arch Linux]
 - Other details that you think may affect.

### Additional context

Here is the error:

/Users/tanvirislam/PROJECTS/QCC/PATIENT_SERVICE_API/venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tanvirislam/PROJECTS/QCC/PATIENT_SERVICE_API/venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/tanvirislam/PROJECTS/QCC/PATIENT_SERVICE_API/venv/lib/python3.12/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/tanvirislam/PROJECTS/QCC/PATIENT_SERVICE_API/venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    config.load()
  File "/Users/tanvirislam/PROJECTS/QCC/PATIENT_SERVICE_API/venv/lib/python3.12/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tanvirislam/PROJECTS/QCC/PATIENT_SERVICE_API/venv/lib/python3.12/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/tanvirislam/PROJECTS/QCC/PATIENT_SERVICE_API/main.py", line 11, in <module>
    from lib import response_models
  File "/Users/tanvirislam/PROJECTS/QCC/PATIENT_SERVICE_API/lib/response_models.py", line 51, in <module>
    class Prescription(BaseModel):
  File "/Users/tanvirislam/PROJECTS/QCC/PATIENT_SERVICE_API/venv/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 92, in __new__
    private_attributes = inspect_namespace(
                         ^^^^^^^^^^^^^^^^^^
  File "/Users/tanvirislam/PROJECTS/QCC/PATIENT_SERVICE_API/venv/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 384, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `prescribing_physician_id = <class 'int'>`. All model fields require a type annotation; if `prescribing_physician_id` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.6/u/model-field-missing-annotation

**Comment by AtVict0r** [comment]
@tanviriss, I wanted to follow up on the status of this issue. Has the bug been resolved? If so, could you please provide some details on the resolution?

**Comment by tanviriss** [comment]
@AtVict0r Yes the bug has been resolved. This was due to the fact that in the response model i put = instead of colons

**Comment by AtVict0r** [comment]
Understood! I appreciate your explanation.
